; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
lib_deps = 
	stm32duino/STM32duino FreeRTOS@^10.3.2
	epsilonrt/Modbus-Ethernet@^1.0.3
	epsilonrt/Modbus-Serial@^2.0.5
	robtillaart/ADS1X15@^0.4.2
    
#board_build.f_cpu = 72000000L

#调速选项,通过stlink可以使用F5进入调速画面
debug_tool = stlink

# 程序上传选项，通过stlink和串口二选一
#stlink上传选项
upload_protocol = stlink

# 串口上传选项
#upload_port = COM13
#upload_protocol = serial
#upload_speed = 115200

# 串口监视器设置
#monitor_port = COM13
#monitor_speed = 115200

# 编译选项,在这里可以添加需要在程序中使用的宏定义
build_flags = 
	-D TCP_KEEP_ALIVE				#开启TCP保活
#	-D USE_HOLDING_REGISTERS_ONLY	#Modbus只使用保持寄存器
	-Wl,-Map= -Wl,--cref

#使用脚本文件，将生成的elf文件转换成hex文件
extra_scripts =Resource/extra_script.py

